import { pgTable } from "../../../schema/basic";
import { integer, timestamp, varchar, pgEnum, decimal } from "drizzle-orm/pg-core";

// Define language type enum based on actual data - extended version
export const languageTypeEnum = pgEnum("language_type", [
  "NEPALI",
  "BHOJPURI", 
  "MAGAR_DHUT",
  "DOTELI",
  "MAGAR_KHAM",
  "URAUN",
  "KULUNG",
  "KHAM",
  "RAJASTHANI",
  "MAJHI",
  "THAMI",
  "BHUJEL",
  "BANGALA",
  "THULUNG",
  "YAKKHA",
  "DHIMAL",
  "TAJPURIYA",
  "ANGIKA",
  "SAMPANG",
  "KHALING",
  "YAMBULE",
  "KUMAL",
  "DARAI",
  "BAHING",
  "BAJURELI",
  "HYOLMO",
  "NACHIRING",
  "YAMPHU",
  "BOTE",
  "GHARE",
  "DUMI",
  "LAPCHA",
  "PUMA",
  "DUMANGLI",
  "DARCHULELI",
  "AATHPAHARIYA",
  "THAKALI",
  "JIREL",
  "MEWAHANG",
  "SYMBOLIC_LANGUAGE",
  "TIBETIAN",
  "MECHE",
  "CHANTYAL",
  "RAJI",
  "LOHARUNG",
  "CHINTANG",
  "GANGAI",
  "PAHARI",
  "DAILEKHI",
  "LHOPA",
  "DURA",
  "KOCHE",
  "CHILING",
  "ENGLISH",
  "JERO",
  "KHAS",
  "SANSKRIT",
  "DOLPALI",
  "HAYU",
  "TILUNG",
  "KOYI",
  "KISAN",
  "WALING",
  "MUSALMAN",
  "HIRAYANWI",
  "JUMLI",
  "PUNJABI",
  "LHOMI",
  "BELHARI",
  "ORIYA",
  "SONAHA",
  "SINDHI",
  "DADELDHURI",
  "BYANSI",
  "AASAMI",
  "KAHMCHI",
  "SAAM",
  "MANAGE",
  "DHULELI",
  "PHANGDUWALI",
  "SUREL",
  "MALPANDE",
  "CHINESE",
  "KHARIYA",
  "KURMALI",
  "BARAM",
  "LINGKHIM",
  "SADHANI",
  "KAGATE",
  "JONGKHA",
  "BANKARIYA",
  "KAIKE",
  "GADHWALI",
  "FRECHN",
  "MIJO",
  "KUKI",
  "KUSUNDA",
  "RUSSIAN",
  "SPANISH",
  "NAGAMIJ",
  "ARABI",
  "OTHER"
]);

export const motherTonguePopulation = pgTable(
  "mother_tongue_population",
  {
    id: varchar("id", { length: 36 }).primaryKey(),

    // Language category
    languageType: languageTypeEnum("language_type").notNull(),

    // Number of people speaking the specified language
    population: integer("population").notNull(),

    // Percentage of total population
    percentage: decimal("percentage", { precision: 5, scale: 2 }),

    // Metadata
    updatedAt: timestamp("updated_at")
      .defaultNow()
      .$onUpdate(() => new Date()),
    createdAt: timestamp("created_at").defaultNow(),
  },
);

export type MotherTonguePopulation = typeof motherTonguePopulation.$inferSelect;
export type NewMotherTonguePopulation = typeof motherTonguePopulation.$inferInsert;

