import { z } from "zod";

// Define the language type enum to match the database enum
export const LanguageTypeEnum = z.enum([
  "NEPALI",
  "BHOJPURI",
  "MAGAR_DHUT",
  "DOTELI",
  "MAGAR_KHAM",
  "URAUN",
  "KULUNG",
  "KHAM",
  "RAJASTHANI",
  "MAJHI",
  "THAMI",
  "BHUJEL",
  "BANGALA",
  "THULUNG",
  "YAKKHA",
  "DHIMAL",
  "TAJPURIYA",
  "ANGIKA",
  "SAMPANG",
  "KHALING",
  "YAMBULE",
  "KUMAL",
  "DARAI",
  "BAHING",
  "BAJURELI",
  "HYOLMO",
  "NACHIRING",
  "YAMPHU",
  "BOTE",
  "GHARE",
  "DUMI",
  "LAPCHA",
  "PUMA",
  "DUMANGLI",
  "DARCHULELI",
  "AATHPAHARIYA",
  "THAKALI",
  "JIREL",
  "MEWAHANG",
  "SYMBOLIC_LANGUAGE",
  "TIBETIAN",
  "MECHE",
  "CHANTYAL",
  "RAJI",
  "LOHARUNG",
  "CHINTANG",
  "GANGAI",
  "PAHARI",
  "DAILEKHI",
  "LHOPA",
  "DURA",
  "KOCHE",
  "CHILING",
  "ENGLISH",
  "JERO",
  "KHAS",
  "SANSKRIT",
  "DOLPALI",
  "HAYU",
  "TILUNG",
  "KOYI",
  "KISAN",
  "WALING",
  "MUSALMAN",
  "HIRAYANWI",
  "JUMLI",
  "PUNJABI",
  "LHOMI",
  "BELHARI",
  "ORIYA",
  "SONAHA",
  "SINDHI",
  "DADELDHURI",
  "BYANSI",
  "AASAMI",
  "KAHMCHI",
  "SAAM",
  "MANAGE",
  "DHULELI",
  "PHANGDUWALI",
  "SUREL",
  "MALPANDE",
  "CHINESE",
  "KHARIYA",
  "KURMALI",
  "BARAM",
  "LINGKHIM",
  "SADHANI",
  "KAGATE",
  "JONGKHA",
  "BANKARIYA",
  "KAIKE",
  "GADHWALI",
  "FRECHN",
  "MIJO",
  "KUKI",
  "KUSUNDA",
  "RUSSIAN",
  "SPANISH",
  "NAGAMIJ",
  "ARABI",
  "OTHER",
]);
export type LanguageType = z.infer<typeof LanguageTypeEnum>;

// Schema for mother tongue population data
export const motherTonguePopulationSchema = z.object({
  id: z.string().optional(),
  languageType: LanguageTypeEnum,
  population: z.number().int().nonnegative(),
  percentage: z.number().min(0).max(100).optional(),
});

// Schema for filtering mother tongue population data
export const motherTonguePopulationFilterSchema = z.object({
  languageType: LanguageTypeEnum.optional(),
});

export const updateMotherTonguePopulationSchema = motherTonguePopulationSchema;

export type MotherTonguePopulationData = z.infer<typeof motherTonguePopulationSchema>;
export type UpdateMotherTonguePopulationData = MotherTonguePopulationData;
export type MotherTonguePopulationFilter = z.infer<typeof motherTonguePopulationFilterSchema>;

